### ISSUE TITLE
@class and @protocol declarations take up too much room

### ISSUE THREAD

**Issue by AriX** [MichaelBuckley/MAIKit#1]
The @class and @protocol declarations at the top of every header file take up a ton of room and make it difficult to read the actual interfaces.

I'd suggest doing: "@class MAIDataAsset, MAILayoutXAxisAnchor, MAILayoutYAxisAnchor, " etc and getting it all taken care of on one line rather than >100 lines being protocol and class declarations.

Additionally, I don't believe it's necessary to to #import TargetConditionals.h if you are importing UIKit and AppKit?

**Comment by MichaelBuckley** [comment]
Absolutely. Improving the readability and formatting of the headers is a high priority for this project, and all those class and protocol declarations are the biggest problems in that regard. They are that way now because I originally envisioned being able to declare just the classes and protocols needed for that header, under the mistaken assumption that the declarations improved the self-documentation of the code, but I never got around to implementing that in the generator.

Combining the declarations into two lines total is a good one, but I think moving them to their own separate header would be even better. Thanks for filing the bug. I'll try to have this fixed soon.

**Comment by AriX** [comment]
Awesome!
